### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by cyr3ne** [mohaldev/teacozy#3]
Good implementation of the required CSS. I know this was just a default project but feel free to play around the color scheme in your future work. The styles are suggestive. 

In Tea Cozy, it doesn't really make sense to change it too much with the dark them, but in Colmar Academy, there is a lot of grey and white as the default style. Color scheme and fonts can be those of your liking if you are design-oriented and have an eye for that. Otherwise, you can just stick with the spec. lol

**Comment by mohaldev** [comment]
Okay. Thanks
